exclude: "^(.*egg.info.*|.*/parameters.py|docs/).*$"
default_language_version:
  python: python3.9
repos:
  - repo: git@github.com:GitGuardian/ggshield.git
    rev: v1.32.2
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          [
            "--multi-line",
            "3",
            "--trailing-comma",
            "--force-grid-wrap",
            "0",
            "--use-parentheses",
            "--ensure-newline-before-comments",
            "--line-length",
            "88",
            "--combine-as",
            "--project",
            "snowflake.connector",
            "--project",
            "snowflake.snowpark",
            "--diff",
          ]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --safe
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: >
          (?x)^(
              .*\.md|
              .*\.yaml
          )$
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
              license_header.txt|
              test/resources/.*|
          )$
      - id: check-yaml
        exclude: >
          (?x)^(
              hypothesis-snowpark/recipe/meta.yaml|
              .github/repo_meta.yaml|
              .*recipe/meta.yaml|
          )$

  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.1.13
    hooks:
      - id: insert-license
        name: insert-py-license
        files: >
          (?x)^(
              hypothesis-snowpark/.*\.py|
              snowpark-checkpoints/.*\.py|
              snowpark-checkpoints-collector/.*\.py|
              test/.*\.py|
          )$
        exclude: >
          (?x)^(
              test/resources/.*\.py|
          )$
        args:
          - --license-filepath
          - license_header.txt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--config=ruff.toml] 
