{% set name = snowpark.checkpoints.configuration" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # need to use path to build on Jenkins
  path: ../

build:
  skip: True
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - python<3.12,>=3.9
    - pip
    - wheel
    - hatchling
  run:
    - python<3.12,>=3.9
    - pydantic>=1.8.2

test:
  imports:
    - snowpark.checkpoints.configuration

about:
  summary: snowpark.checkpoints.configuration
