{% set name = "snowpark-checkpoints-configuration" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script: |
    set -e
    {{ PYTHON }} -m pip install . --no-deps -vvv  

requirements:
  host:
    - python<3.12,>=3.9
    - pip
    - wheel
    - hatchling
  run:
    - python<3.12,>=3.9
    - pydantic>=1.8.2
    - snowflake-snowpark-python>=1.26.0

test:
  requires:
    - pip
    - snowflake-snowpark-python>=1.26.0
    - pandas
    - pydantic
  commands:
    - pip check

about:
  summary: A package for snowpark checkpoints configuration
