#
# Copyright (c) 2012-2024 Snowflake Computing Inc. All rights reserved.
#

from typing import Final


#Tables names
SNOWPARK_CHECKPOINTS_REPORT_TABLE_NAME: Final[str] = "SNOWPARK_CHECKPOINTS_REPORT"
SNOWPARK_CHECKPOINTS_PERFORMANCE_TEST_TABLE_NAME: Final[str] = (
    "SNOWPARK_CHECKPOINTS_PERFORMANCE_TEST"
)

#Columns names
JOB_COLUMN_NAME: Final[str] = "JOB"
STATUS_COLUMN_NAME: Final[str] = "STATUS"
CHECKPOINT_COLUMN_NAME: Final[str] = "CHECKPOINT"
MESSAGE_COLUMN_NAME: Final[str] = "MESSAGE"
DATA_COLUMN_NAME: Final[str] = "DATA"
DATE_COLUMN_NAME: Final[str] = "DATE"
EXECUTION_MODE_COLUMN_NAME: Final[str] = "EXECUTION_MODE"
MEMORY_COLUMN_NAME: Final[str] = "MEMORY"
TIME_COLUMN_NAME: Final[str] = "TIME"
PACKAGE_COLUMN_NAME: Final[str] = "PACKAGE_NAME"
PACKAGE_VERSION_COLUMN_NAME: Final[str] = "PACKAGE_VERSION"
SOURCE_IN_COLUMN_NAME: Final[str] = "SOURCE_IN"
SOURCE_SIZE_COLUMN_NAME: Final[str] = "SOURCE_SIZE"
ERROR_MEMORY_COLUMN_NAME: Final[str] = "ERROR_MEMORY"
ERROR_TIME_COLUMN_NAME: Final[str] = "ERROR_TIME"
EXECUTION_DATE_COLUMN_NAME: Final[str] = "EXECUTION_DATE"
RESULT_COLUMN_NAME: Final[str] = "RESULT"

#Queries
SQL_CREATE_PERFORMANCE_TABLE = f"CREATE OR REPLACE TABLE {SNOWPARK_CHECKPOINTS_PERFORMANCE_TEST_TABLE_NAME} ({EXECUTION_DATE_COLUMN_NAME} TIMESTAMP_TZ, {PACKAGE_COLUMN_NAME} VARCHAR, {PACKAGE_VERSION_COLUMN_NAME} VARCHAR, {SOURCE_IN_COLUMN_NAME} VARCHAR, {SOURCE_SIZE_COLUMN_NAME} VARCHAR, {EXECUTION_MODE_COLUMN_NAME} VARCHAR, {MEMORY_COLUMN_NAME} FLOAT, {TIME_COLUMN_NAME} FLOAT, {ERROR_MEMORY_COLUMN_NAME} VARCHAR, {ERROR_TIME_COLUMN_NAME} VARCHAR);"

#Paths
STRESS_INPUT_CSV_PATH: Final[str] = "snowpark-checkpoints-testing/src/utils/source_in/stress_input/data_input_medium.csv"
E2E_INPUT_CSV_PATH: Final[str] = "snowpark-checkpoints-testing/src/utils/source_in/e2e_input/data_e2e_test.csv"
SNOWPARK_CHECKPOINTS_OUTPUT_DIRECTORY_NAME: Final[str] = "snowpark-checkpoints-output"
TESTS_FOLDER_NAME: Final[str] = "snowpark-checkpoints-testing"

#Packages names
PACKAGE_NAME_COLLECTORS: Final[str] = "collectors"
PACKAGE_NAME_VALIDATORS: Final[str] = "validators"

#Limits keys
LIMIT_SUP_MEMORY_KEY: Final[str] = "sup_memory"
LIMIT_SUP_TIME_KEY: Final[str] = "sup_time"