name: Build Documentation Artifacts

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!Demos/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "**"
      - "!Demos/**"
  workflow_call:

env:
  PYTHON_VERSION: "3.11"

permissions:
  contents: read
  pull-requests: write

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Display workflow environment
        run: python .github/scripts/py_show_env.py

      - name: Install required tools
        run: |
          python -m pip install --upgrade pip -q
          pip install hatch -q
          pip list
          hatch --version

      - name: Build documentation
        run: |
          echo "Current working directory:" && pwd
          hatch run docs:build
        shell: bash

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/build/html
