name: Build wheels [snowpark_checkpoints_configuration]

on: workflow_call

env:
  PYTHON_VERSION: "3.11"

permissions:
  contents: read
  pull-requests: write

jobs:
  wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install required tools
        run: |
          python -m pip install --upgrade pip -q
          pip install hatch -q
          pip list
          hatch status
          hatch env show
          hatch --version

      - name: Generate wheel and sdist
        run: hatch build
        working-directory: ./snowpark-checkpoints-configuration

      - name: Show generated artifacts
        run: |
          echo "Current directory: $PWD" && ls -la dist
        working-directory: ./snowpark-checkpoints-configuration

      - name: Verify build artifacts
        run: |
          python -m venv wheelvenv
          wheelvenv/bin/pip install --upgrade pip -q
          wheelvenv/bin/pip install dist/*.whl -q
          wheelvenv/bin/pip list
          wheelvenv/bin/pip show $PACKAGE_NAME
        working-directory: ./snowpark-checkpoints-configuration
        env:
          PACKAGE_NAME: snowpark-checkpoints-configuration
