name: Build and test wheel artifacts for hypothesis-snowpark

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

jobs:
  wheels:
    name: Build and test wheels
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install required tools
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          hatch --version

      - name: Generate wheel and sdist
        run: hatch build
        working-directory: ./hypothesis-snowpark

      - name: Show generated artifacts
        run: ls -lha dist/

      - name: Verify build artifacts
        run: |
          python -m venv wheelvenv
          wheelvenv/bin/pip install --upgrade pip
          wheelvenv/bin/pip install dist/*.whl
          wheelvenv/bin/pip list
          wheelvenv/bin/pip show hypothesis-snowpark

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist/*
