name: Run all workflows [hypothesis.snowpark]

on:
  push:
    branches:
      - main
    paths:
        - "**"
        - "!snowpark-checkpoints/**"
        - "!snowpark-checkpoints-collector/**"
        - "!Demos/**"
    tags:
      - 'hypothesis.snowpark-v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: '**'
    paths:
        - "**"
        - "!snowpark-checkpoints/**"
        - "!snowpark-checkpoints-collector/**"
        - "!Demos/**"
  workflow_call:

jobs:
  lint:
    name: Static analysis and linting for hypothesis-snowpark
    uses: ./.github/workflows/hypothesis-snowpark-lint.yml

  build:
    needs: lint
    name: Build and test wheels for hypothesis-snowpark
    uses: ./.github/workflows/hypothesis-snowpark-use-build-wheels.yml
    secrets: inherit

  test:
    needs: build
    name: Run all tests for hypothesis-snowpark
    uses: ./.github/workflows/hypothesis-snowpark-use-tests_all.yml
    secrets: inherit

  publish:
    needs: test
    name: Publish package hypothesis-snowpark
    uses: ./.github/workflows/hypothesis-snowpark-use-set-artifacts.yml
    secrets: inherit
    with:
        artifact-name: hypothesis-snowpark
