name: Publish to PyPI [hypothesis.snowpark]

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

jobs:
  download-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Verify package contents
        run: |
          echo "Current working directory: $PWD"
          ls -la dist/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine sigstore
          pip list
