name: Run All workflows [snowpark_checkpoints]

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!snowpark-checkpoints-collector/**"
      - "!hypothesis-snowpark/**"
      - "!Demos/**"
  pull_request:
    branches: "**"
    paths:
      - "**"
      - "!snowpark-checkpoints-collector/**"
      - "!hypothesis-snowpark/**"
      - "!Demos/**"
  workflow_call:

jobs:
  lint:
    name: Static analysis and linting snowpark-checkpoints-collector
    uses: ./.github/workflows/snowpark_checkpoints-lint.yml

  build:
    needs: lint
    name: Build wheels snowpark-checkpoints-collector
    uses: ./.github/workflows/snowpark_checkpoints-use-build-wheels.yml
    secrets: inherit

  test:
    needs: build
    name: Run all tests snowpark-checkpoints-collector
    uses: ./.github/workflows/snowpark_checkpoints-use-tests_all.yml
    secrets: inherit

  artifact:
    needs: test
    name: Artifact package snowpark-checkpoints-collector
    uses: ./.github/workflows/snowpark_checkpoints-use-set-artifacts.yml
    secrets: inherit
    with:
      artifact-name: snowpark-checkpoints
