name: Publish All Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches: "**"

permissions: write-all

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine sigstore hatch
          pip list

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install GitVersion
        run: |
          dotnet tool install --global GitVersion.Tool
          echo "export PATH=\$PATH:\$HOME/.dotnet/tools" >> $GITHUB_ENV

      - name: Generate Version
        id: gitversion
        run: |
          version_info=$(dotnet gitversion /output json /showvariable InformationalVersion)
          version_output=$(dotnet gitversion /output json /showvariable MajorMinorPatch)
          echo "Calculated Version: $version_output" && echo "Informational Version: $version_info"
          echo "version=$version_output" >> $GITHUB_OUTPUT
        env:
          DOTNET_ROOT: $HOME/.dotnet

      - name: Update Version [hypothesis.snowpark]
        run: |
          sed -i "s/^version = \".*\"/version = \"${NEW_VERSION}\"/" pyproject.toml
          echo "Package Version updated:"
          grep "version = " pyproject.toml
        env:
          NEW_VERSION: ${{ steps.gitversion.outputs.version }}
        working-directory: ./hypothesis-snowpark

      - name: Generate Package [hypothesis.snowpark]
        run: |
          hatch build
          echo "Current directory: $PWD" && ls -la dist
        working-directory: ./hypothesis-snowpark

      - name: Update Version [snowpark-checkpoints-collector]
        run: |
          sed -i "s/^version = \".*\"/version = \"${NEW_VERSION}\"/" pyproject.toml
          echo "Package Version updated:"
          grep "version = " pyproject.toml
        env:
          NEW_VERSION: ${{ steps.gitversion.outputs.version }}
        working-directory: ./snowpark-checkpoints-collector

      - name: Generate Package [snowpark-checkpoints-collector]
        run: |
          hatch build
          echo "Current directory: $PWD" && ls -la dist
        working-directory: ./snowpark-checkpoints-collector

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-snowpark-checkpoints
          path: dist/*

  publish:
    name: Publish Packages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: all-snowpark-checkpoints
          path: ./dist

      - name: Verify artifacts
        run: |
          echo "Current working directory: $PWD"
          ls -la dist/
