name: Publish All Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip -q
          pip install build twine sigstore hatch -q
          pip list

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install GitVersion
        run: |
          dotnet tool install --global GitVersion.Tool
          echo "export PATH=\$PATH:\$HOME/.dotnet/tools" >> $GITHUB_ENV

      - name: Generate Version
        id: gitversion
        run: |
          version_info=$(dotnet gitversion /output json /showvariable InformationalVersion)
          version_output=$(dotnet gitversion /output json /showvariable MajorMinorPatch)
          echo "Calculated Version: $version_output" && echo "Informational Version: $version_info"
          echo "version=$version_output" >> $GITHUB_OUTPUT
        env:
          DOTNET_ROOT: $HOME/.dotnet

      - name: Update Version [snowpark-checkpoints]
        run: |
          echo "Current directory: $PWD" && ls -la
          sed -i "s/^__version__ = \".*\"/__version__ = \"${NEW_VERSION}\"/" ${FILE_VERSION}
          echo "Package Version updated:" && cat ${FILE_VERSION}
        env:
          NEW_VERSION: ${{ steps.gitversion.outputs.version }}
          FILE_VERSION: __version__.py
        working-directory: ${{ github.workspace }}

      - name: Update Version [snowpark-configuration]
        run: |
          echo "Current directory: $PWD" && ls -la
          sed -i "s/^__version__ = \".*\"/__version__ = \"${NEW_VERSION}\"/" ${FILE_VERSION}
          echo "Package Version updated:" && cat ${FILE_VERSION}
        env:
          NEW_VERSION: ${{ steps.gitversion.outputs.version }}
          FILE_VERSION: ../snowpark-checkpoints-configuration/__version__.py
        working-directory: ${{ github.workspace }}

      - name: Update Version [snowpark-checkpoints-hypothesis]
        run: |
          sed -i "s/^__version__ = \".*\"/__version__ = \"${NEW_VERSION}\"/" ${FILE_VERSION}
          echo "Package Version updated:" && cat ${FILE_VERSION}
        env:
          NEW_VERSION: ${{ steps.gitversion.outputs.version }}
          FILE_VERSION: ../snowpark-checkpoints-hypothesis/__version__.py
        working-directory: ./snowpark-checkpoints-hypothesis

      - name: Update Version [snowpark-checkpoints-validators]
        run: |
          sed -i "s/^__version__ = \".*\"/__version__ = \"${NEW_VERSION}\"/" ${FILE_VERSION}
          echo "Package Version updated:" && cat ${FILE_VERSION}
        env:
          NEW_VERSION: ${{ steps.gitversion.outputs.version }}
          FILE_VERSION: ../snowpark-checkpoints-validators/__version__.py
        working-directory: ./snowpark-checkpoints-validators

      - name: Update Version [snowpark-checkpoints-collector]
        run: |
          sed -i "s/^__version__ = \".*\"/__version__ = \"${NEW_VERSION}\"/" ${FILE_VERSION}
          echo "Package Version updated:" && cat ${FILE_VERSION}
        env:
          NEW_VERSION: ${{ steps.gitversion.outputs.version }}
          FILE_VERSION: ../snowpark-checkpoints-collectors/__version__.py
        working-directory: ./snowpark-checkpoints-collectors

      - name: Generate Package [snowpark-checkpoints]
        run: |
          hatch build
          echo "Current directory: $PWD" && ls -la dist
        working-directory: ${{ github.workspace }}

      - name: Generate Package [snowpark-configuration]
        run: |
          hatch build
          echo "Current directory: $PWD" && ls -la dist
        working-directory: ./snowpark-checkpoints-configuration

      - name: Generate Package [snowpark-checkpoints-hypothesis]
        run: |
          hatch build
          echo "Current directory: $PWD" && ls -la dist
        working-directory: ./snowpark-checkpoints-hypothesis

      - name: Generate Package [snowpark-checkpoints-validators]
        run: |
          hatch build
          echo "Current directory: $PWD" && ls -la dist
        working-directory: ./snowpark-checkpoints-validators

      - name: Generate Package [snowpark-checkpoints-collector]
        run: |
          hatch build
          echo "Current directory: $PWD" && ls -la dist
        working-directory: ./snowpark-checkpoints-collectors

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-snowpark-checkpoints
          path: |
            ./dist/*
            ./**/dist/*


  publish:
    name: Publish Packages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: all-snowpark-checkpoints
          path: ./dist

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify Artifacts
        run: |
          echo "Current working directory: $PWD" && ls -la
          python -m pip install --upgrade pip -q
          python -m venv wheelvenv
          wheelvenv/bin/pip install --upgrade pip -q
          wheelvenv/bin/pip install dist/*.whl -q
          wheelvenv/bin/pip list
          wheelvenv/bin/pip show $PACKAGE_NAME
        working-directory: ./dist
        env:
          PACKAGE_NAME: snowpark-checkpoints

      - name: Install Dependencies
        run: |
          pip install build twine sigstore -q
