name: Build and Test Conda Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.11"
  CONDA_ENV_NAME: "snow_3_11"

jobs:
  build:
    name: Build Conda Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Initialize Conda
        run: |
          conda init bash
          source ~/.bashrc

      - name: Conda Create environment
        run: |
          conda create --name ${{ env.CONDA_ENV_NAME }} -c https://repo.anaconda.com/pkgs/snowflake python=${{ env.PYTHON_VERSION }} -y
          source ~/.bashrc
          conda activate ${{ env.CONDA_ENV_NAME }}
          conda info --envs
          conda info

      - name: Conda Setup environment
        run: |
          source ~/.bashrc
          conda activate ${{ env.CONDA_ENV_NAME }}
          conda config --add channels conda-forge
          conda install -c conda-forge pytest conda-build conda-verify -y
          conda list

      - name: Build Conda Package [snowpark-configuration]
        run: |
          source ~/.bashrc
          conda activate ${{ env.CONDA_ENV_NAME }}
          echo "Current directory: $PWD" && ls -la
          conda build recipe/ -c conda-forge --python=3.11 --numpy=1.23 --output-folder recipe/dist
          ls -l recipe/dist
        working-directory: ./snowpark-checkpoints-configuration
