name: Run All workflows [snowpark_checkpoints_collector]

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!snowpark-checkpoints/**"
      - "!hypothesis-snowpark/**"
      - "!Demos/**"
    tags:
      - "hypothesis.snowpark-v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: "**"
    paths:
      - "**"
      - "!snowpark-checkpoints/**"
      - "!hypothesis-snowpark/**"
      - "!Demos/**"
  workflow_call:

jobs:
  lint:
    name: Static analysis and linting snowpark-checkpoints-collector
    uses: ./.github/workflows/snowpark_checkpoints_collector-lint.yml

  build:
    needs: lint
    name: Build wheels snowpark-checkpoints-collector
    uses: ./.github/workflows/snowpark_checkpoints_collector-use-build-wheels.yml
    secrets: inherit

  test:
    needs: build
    name: Run all tests snowpark-checkpoints-collector
    uses: ./.github/workflows/snowpark_checkpoints_collector-use-tests_all.yml
    secrets: inherit

  artifact:
    needs: test
    name: Artifact package snowpark-checkpoints-collector
    uses: ./.github/workflows/snowpark_checkpoints_collector-use-set-artifacts.yml
    secrets: inherit
    with:
      artifact-name: snowpark-checkpoints-collector
